[package]
name = "json_query_cli"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/backend"
]

[dependencies]
clap = { version = "4", features = ["derive"] }
# argh =  "0.1.13"
