[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[lib]
path = "downloader.rs"

[dependencies]
reqwest = { version = "0.12.20", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"